# ---------------------------------------------------------------------------
# defineproj.py
# Created on: 2012-07-28 09:24:54.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
test = "C:\\CHANG\\PRISM\\PRISM_Analysis\\test"

# Process: Define Projection
arcpy.DefineProjection_management(test, "GEOGCS['GCS_WGS_1972',DATUM['D_WGS_1972',SPHEROID['WGS_1972',6378135.0,298.26]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

