# ---------------------------------------------------------------------------
# Raster_It.py
# Created on: 2012-07-25 08:43:00.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
v1890-1920 = "C:\\CHANG\\PRISM\\ppt\\PACE_Rasters\\1890-1920"
v1890-1920__2_ = "C:\\CHANG\\PRISM\\ppt\\PACE_Rasters\\1890-1920"

# Process: Iterate Rasters
arcpy.IterateRasters_mb(v1890-1920, "", "IMG", "RECURSIVE")

# Process: Mosaic To New Raster
arcpy.MosaicToNewRaster_management("C:\\CHANG\\PRISM\\ppt\\PACE_Rasters\\1890-1920\\us_ppt_1895.04.img", v1890-1920__2_, "1890-1920ppt", "", "8_BIT_UNSIGNED", "", "1", "MEAN", "FIRST")

